<%@ Page Title="Welcome to Infanos" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Infanos._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <h1><%: Title %></h1>
    <h2>Infanos, gaming leveled up!</h2>
    <p class="lead">We at Infanos strive to provide the absolute best deals on all things gaming
        along with delivering in depth reviews generated by YOU, the user. Get your thumbs ready
        so you can outclass the competition!
    </p>
</asp:Content>
